-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.customer
(
    customer_id integer NOT NULL,
    customer_name character varying(100) COLLATE pg_catalog."default",
    customer_email character varying(256) COLLATE pg_catalog."default",
    customer_since date,
    customer_card_number character varying(20) COLLATE pg_catalog."default",
    birthdate date,
    gender character(1) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (customer_id)
);

CREATE TABLE IF NOT EXISTS public.product
(
    product_id integer NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description character varying(256) COLLATE pg_catalog."default",
    price numeric(8, 2) NOT NULL,
    type_id integer,
    CONSTRAINT product_pkey PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    type_id integer NOT NULL,
    product_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    product_category character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT product_type_pkey PRIMARY KEY (type_id)
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    detail_id integer NOT NULL,
    transaction_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    price numeric(8, 2) NOT NULL,
    CONSTRAINT sales_detail_pkey PRIMARY KEY (detail_id)
);

CREATE TABLE IF NOT EXISTS public.sales_outlet
(
    sales_outlet_id integer NOT NULL,
    sales_outlet_type character varying(20) COLLATE pg_catalog."default",
    address character varying(100) COLLATE pg_catalog."default",
    city character varying(25) COLLATE pg_catalog."default",
    telephone character varying(20) COLLATE pg_catalog."default",
    postal_code integer,
    manager_id integer,
    CONSTRAINT sales_outlet_pkey PRIMARY KEY (sales_outlet_id)
);

CREATE TABLE IF NOT EXISTS public.sales_transaction
(
    transaction_id integer NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    sales_outlet_id integer NOT NULL,
    staff_id integer NOT NULL,
    customer_id integer,
    CONSTRAINT sales_transaction_pkey PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public.staff
(
    staff_id integer NOT NULL,
    first_name character varying(25) COLLATE pg_catalog."default",
    last_name character varying(25) COLLATE pg_catalog."default",
    "position" character varying(25) COLLATE pg_catalog."default",
    start_date date,
    location character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT staff_pkey PRIMARY KEY (staff_id)
);

ALTER TABLE IF EXISTS public.product
    ADD CONSTRAINT product_type_id_fkey FOREIGN KEY (type_id)
    REFERENCES public.product_type (type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD CONSTRAINT sales_detail_product_id_fkey FOREIGN KEY (product_id)
    REFERENCES public.product (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD CONSTRAINT sales_detail_transaction_id_fkey FOREIGN KEY (transaction_id)
    REFERENCES public.sales_transaction (transaction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_transaction
    ADD CONSTRAINT sales_transaction_customer_id_fkey FOREIGN KEY (customer_id)
    REFERENCES public.customer (customer_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_transaction
    ADD CONSTRAINT sales_transaction_sales_outlet_id_fkey FOREIGN KEY (sales_outlet_id)
    REFERENCES public.sales_outlet (sales_outlet_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_transaction
    ADD CONSTRAINT sales_transaction_staff_id_fkey FOREIGN KEY (staff_id)
    REFERENCES public.staff (staff_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;